### PR TITLE
Update Cartfile

### PR DESCRIPTION
**Pull request by chamira-at**
Carthage file was not updated. this PR update the Cartfile

To Install Carthage -> https://formulae.brew.sh/formula/carthage

then run `carthage update --cache-builds` to resolved dependencies

### CODE REVIEW

**Comment by eirikvaa** [comment]
Why is this pointing to `master` and not https://github.com/Airthings/RxBluetoothKit/pull/9?

**Comment by chamira-at** [comment]
> Why is this pointing to `master` and not #9?

#9 is only for release as far as I understood. Updating Cartfile is pretty much like updating cocoapod spec and SPM.

**Comment by eirikvaa** [comment]
I'm running into all sorts of issues:

```
RxBluetoothKit on  fix-cartfile via ﯣ
❯ carthage update --cache-builds
*** Fetching RxSwift
*** Checking out RxSwift at "6.5.0"
*** xcodebuild output can be found in /var/folders/52/tzqs06d57058msg9r02l0dkc0000gn/T/carthage-xcodebuild.ZyCyGZ.log
*** Invalid cache found for RxSwift, rebuilding with all downstream dependencies
*** Downloading RxSwift binary at "Atlas"
*** Building scheme "RxSwift" in Rx.xcworkspace
A shell task (/usr/bin/xcrun lipo -create /Users/eirik/Library/Caches/org.carthage.CarthageKit/DerivedData/14.2_14C18/RxSwift/6.5.0/Build/Intermediates.noindex/ArchiveIntermediates/RxSwift/IntermediateBuildFilesPath/UninstalledProducts/watchos/RxSwift.framework/RxSwift /Users/eirik/Library/Caches/org.carthage.CarthageKit/DerivedData/14.2_14C18/RxSwift/6.5.0/Build/Products/Release-watchsimulator/RxSwift.framework/RxSwift -output /Users/eirik/Documents/Jobb/Airthings/Kode/RxBluetoothKit/Carthage/Build/watchOS/RxSwift.framework/RxSwift) failed with exit code 1:
fatal error: /Applications/Xcode-14.2.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: /Users/eirik/Library/Caches/org.carthage.CarthageKit/DerivedData/14.2_14C18/RxSwift/6.5.0/Build/Intermediates.noindex/ArchiveIntermediates/RxSwift/IntermediateBuildFilesPath/UninstalledProducts/watchos/RxSwift.framework/RxSwift and /Users/eirik/Library/Caches/org.carthage.CarthageKit/DerivedData/14.2_14C18/RxSwift/6.5.0/Build/Products/Release-watchsimulator/RxSwift.framework/RxSwift have the same architectures (arm64) and can't be in the same fat output file

Building universal frameworks with common architectures is not possible. The device and simulator slices for "RxSwift" both build for: arm64
Rebuild with --use-xcframeworks to create an xcframework bundle instead.

RxBluetoothKit on  fix-cartfile via ﯣ v5.7.2 took 1m13s
❯ carthage update --cache-builds --use-xcframeworks
*** Fetching RxSwift
*** Checking out RxSwift at "6.5.0"
*** xcodebuild output can be found in /var/folders/52/tzqs06d57058msg9r02l0dkc0000gn/T/carthage-xcodebuild.haTmOK.log
*** Invalid cache found for RxSwift, rebuilding with all downstream dependencies
*** Downloading RxSwift binary at "Atlas"

RxBluetoothKit on  fix-cartfile via ﯣ v5.7.2 took 9s
❯ carthage build --cache-builds --use-xcframeworks && carthage archive RxBluetoothKit
*** xcodebuild output can be found in /var/folders/52/tzqs06d57058msg9r02l0dkc0000gn/T/carthage-xcodebuild.Twvch0.log
*** Valid cache found for RxSwift, skipping build
Could not find any copies of RxBluetoothKit.framework. Make sure you're in the project's root and that the frameworks have already been built using 'carthage build --no-skip-current'.

RxBluetoothKit on  fix-cartfile via ﯣ v5.7.2
❯ carthage build --no-skip-current --cache-builds --use-xcframeworks && carthage archive RxBluetoothKit
*** xcodebuild output can be found in /var/folders/52/tzqs06d57058msg9r02l0dkc0000gn/T/carthage-xcodebuild.Eib8fz.log
*** Valid cache found for RxSwift, skipping build
*** Building scheme "RxBluetoothKit watchOS" in RxBluetoothKit.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/eirik/Documents/Jobb/Airthings/Kode/RxBluetoothKit/RxBluetoothKit.xcodeproj -scheme RxBluetoothKit\ watchOS -configuration Release -sdk watchsimulator -destination platform=watchOS\ Simulator,id=200D4725-877E-4903-B4DF-7EB2FF67B2DC -destination-timeout 3 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build VALIDATE_WORKSPACE=NO FRAMEWORK_SEARCH_PATHS=$(inherited)\ /var/folders/52/tzqs06d57058msg9r02l0dkc0000gn/T/carthage-xcframework-5HnR (launched in /Users/eirik/Documents/Jobb/Airthings/Kode/RxBluetoothKit)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/52/tzqs06d57058msg9r02l0dkc0000gn/T/carthage-xcodebuild.Eib8fz.log

RxBluetoothKit on  fix-cartfile via ﯣ v5.7.2 took 35s
```

**Comment by chamira-at** [comment]
hmm. I dont have this problem but I have when I try to build the archive :(

**Comment by chamira-at** [comment]
It looks like Carthage has some issues. https://github.com/Carthage/Carthage/blob/master/Documentation/Xcode12Workaround.md

Are you okay if we leave it for the time being and move forward? my suggestion is just merge this and release SPM and Cocoapod

**Review by eirikvaa — APPROVED** [review]

**Pull request merged**
